DROP TABLE IF EXISTS WTC_RELEASES;

CREATE TABLE WTC_RELEASES
(
    RLS_ID                  NUMBER(10) AUTO_INCREMENT PRIMARY KEY,
    RLS_USER_NAME           VARCHAR2(100),
    RLS_PROJECT_NAME        VARCHAR2(100),
    RLS_URL                 VARCHAR2(500),
    RLS_LAST_UPDATE_DATE    DATE,
    RLS_LAST_CHECK_DATE     DATE,
    RLS_VERSION             VARCHAR2(1000) NOT NULL
);

ALTER TABLE WTC_RELEASES
    ADD CONSTRAINT WTC_RELEASES UNIQUE(RLS_USER_NAME, RLS_PROJECT_NAME);